---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sidekiq-deployment
  labels:
    app: sidekiq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sidekiq
  template:
    metadata:
      labels:
        app: sidekiq
    spec:
      containers:
      - name: sidekiq
        image: jlphillips/circuitverse_sidekiq
        volumeMounts:
        - name: bundle
          mountPath: /circuitverse/.bundle
        - name: node-modules
          mountPath: /circuitverse/node_modules
        - name: circuitverse
          mountPath: .:/circuitverse
        - name: database
          mountPath: ./config/database.docker.yml:/circuitverse/config/database.yml
        env:
          - name: REDIS_URL
            value: "redis://redis:6379/0"
          - name: COMM_ARG
            value: "exec sidekiq -q default -q mailers"
        command: ["bundle"]
        args: ["exec","sidekiq","-q","default","-q","mailers"]
        ports:
        - containerPort: 6379
      volumes:
        - name: bundle
          emptyDir: {}
        - name: node-modules
          emptyDir: {}
        - name: circuitverse
          emptyDir: {}
        - name: database
          emptyDir: {}
