apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: jlphillips/circuitverse_web
        command: ["/circuitverse/bin/docker_run"]
        volumeMounts:
          - name: circuitverse
            mountPath: /circuitverse
          - name: bundle
            mountPath: /circuitverse/.bundle
          - name: node-modules
            mountPath: /circuitverse/node_modules
          - name: database
            mountPath: /circuitverse/config/database.yml
            subPath: database.docker.yml
        env:
          - name: REDIS_URL
            value: "redis://redis:6379/0"
          - name: CIRCUITVERSE_USE_SOLR
            value: "false"
          - name: WEBPACKER_DEV_SERVER_HOST
            value: "webpacker"
        ports:
          - containerPort: 3000
      volumes:
        - name: circuitverse
          hostPath:
            path: /home/jphillips/CircuitVerse
        - name: bundle
          hostPath:
            path: /home/jphillips/CircuitVerse/.bundle
        - name: node-modules
          hostPath:
            path: /home/jphillips/CircuitVerse/node-modules
        - name: database
          hostPath:
            path: /home/jphillips/CircuitVerse/config
---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000