apiVersion: apps/v1
kind: Deployment
metadata:
  name: webpacker-deployment
  labels:
    app: webpacker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webpacker
  template:
    metadata:
      labels:
        app: webpacker
    spec:
      containers:
      - name: webpacker
        image: jlphillips/circuitverse_webpacker
        command: ["/bin/sh","-c"]
        args: ["yarn install --check-files && /circuitverse/bin/docker_webpacker_run"]
        volumeMounts:
          - name: circuitverse
            mountPath: /circuitverse
          - name: bundle
            mountPath: /circuitverse/.bundle
          - name: node-modules
            mountPath: /circuitverse/node_modules
        env:
          - name: NODE_ENV
            value: "development"
          - name: RAILS_ENV
            value: "development"
          - name: WEBPACKER_DEV_SERVER_HOST
            value: "0.0.0.0"
        ports:
          - containerPort: 3035
      volumes:
        - name: circuitverse
          hostPath:
            path: /home/jphillips/CircuitVerse
        - name: bundle
          hostPath:
            path: /home/jphillips/CircuitVerse/.bundle
        - name: node-modules
          hostPath:
            path: /home/jphillips/CircuitVerse/node_modules
---
apiVersion: v1
kind: Service
metadata:
  name: webpacker
spec:
  selector:
    app: webpacker
  ports:
    - protocol: TCP
      port: 3035
      targetPort: 3035
